services:
  - type: web
    name: Chosmochords
    env: static
    buildCommand: "npm install --force @vanilla-extract/css@latest @vanilla-extract/vite-plugin@latest vite@latest --legacy-peer-deps && npm install && npm run build"
    staticPublishPath: dist
